language: node_js
node_js:
  - "16"
install:
    - npm install
script:
    - npm run build
env:
    - PORT=5000
    - DB_USER=test
    - DB_PWD=12345
    - DB_NAME=sample_todolist
    - JWT_SIGN=save
deploy:
  provider: heroku
  edge: true
  api_key: c29393c2-1b87-4232-b688-b3a016b45f7d
  app: react-node-facebook
  on:
    all_branches: true

