language: node_js
node_js:
  - "16"
install:
    - npm install
script:
    - npm run build
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: c905e2cc-8261-4fb4-ae98-ee82ad9776f0
  app: react-node-facebook
